services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    env_file: .env
    healthcheck:
      test: "pg_isready -h postgres_db"
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - common
  
  mysql_db:
    container_name: mysql_db
    image: mysql:9.3.0
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql 
    networks:
      - common

networks:
  common:

volumes:
  mysql_data:
